package endpoints

import "fmt"

// activityNames maps Suunto/Sports-Tracker ActivityType IDs to their enum names
// as decompiled from the shipping APK (com.stt.android.suunto). IDs 89 and 98
// are gaps in the wire enum.
var activityNames = map[int]string{
	0:   "WALKING",
	1:   "RUNNING",
	2:   "CYCLING",
	3:   "CROSS_COUNTRY_SKIING",
	4:   "OTHER_1",
	5:   "OTHER_2",
	6:   "OTHER_3",
	7:   "OTHER_4",
	8:   "OTHER_5",
	9:   "OTHER_6",
	10:  "MOUNTAIN_BIKING",
	11:  "HIKING",
	12:  "ROLLER_SKATING",
	13:  "DOWNHILL_SKIING",
	14:  "PADDLING",
	15:  "ROWING",
	16:  "GOLF",
	17:  "INDOOR",
	18:  "PARKOUR",
	19:  "BALLGAMES",
	20:  "OUTDOOR_GYM",
	21:  "SWIMMING",
	22:  "TRAIL_RUNNING",
	23:  "GYM",
	24:  "NORDIC_WALKING",
	25:  "HORSEBACK_RIDING",
	26:  "MOTOR_SPORTS",
	27:  "SKATEBOARDING",
	28:  "WATER_SPORTS",
	29:  "CLIMBING",
	30:  "SNOWBOARDING",
	31:  "SKI_TOURING",
	32:  "FITNESS_CLASS",
	33:  "SOCCER",
	34:  "TENNIS",
	35:  "BASKETBALL",
	36:  "BADMINTON",
	37:  "BASEBALL",
	38:  "VOLLEYBALL",
	39:  "AMERICAN_FOOTBALL",
	40:  "TABLE_TENNIS",
	41:  "RACQUETBALL",
	42:  "SQUASH",
	43:  "FLOORBALL",
	44:  "HANDBALL",
	45:  "SOFTBALL",
	46:  "BOWLING",
	47:  "CRICKET",
	48:  "RUGBY",
	49:  "ICE_SKATING",
	50:  "ICE_HOCKEY",
	51:  "YOGA",
	52:  "INDOOR_CYCLING",
	53:  "TREADMILL",
	54:  "CROSSFIT",
	55:  "CROSSTRAINER",
	56:  "ROLLER_SKIING",
	57:  "INDOOR_ROWING",
	58:  "STRETCHING",
	59:  "TRACK_AND_FIELD",
	60:  "ORIENTEERING",
	61:  "SUP",
	62:  "COMBAT_SPORTS",
	63:  "KETTLEBELL",
	64:  "DANCING",
	65:  "SNOWSHOEING",
	66:  "FRISBEE_GOLF",
	67:  "FUTSAL",
	68:  "MULTISPORT",
	69:  "AEROBICS",
	70:  "TREKKING",
	71:  "SAILING",
	72:  "KAYAKING",
	73:  "CIRCUIT_TRAINING",
	74:  "TRIATHLON",
	75:  "PADEL",
	76:  "CHEERLEADING",
	77:  "BOXING",
	78:  "SCUBADIVING",
	79:  "FREEDIVING",
	80:  "ADVENTURE_RACING",
	81:  "GYMNASTICS",
	82:  "CANOEING",
	83:  "MOUNTAINEERING",
	84:  "TELEMARKSKIING",
	85:  "OPENWATER_SWIMMING",
	86:  "WINDSURFING",
	87:  "KITESURFING_KITING",
	88:  "PARAGLIDING",
	90:  "SNORKELING",
	91:  "SURFING",
	92:  "SWIMRUN",
	93:  "DUATHLON",
	94:  "AQUATHLON",
	95:  "OBSTACLE_RACING",
	96:  "FISHING",
	97:  "HUNTING",
	99:  "GRAVEL_CYCLING",
	100: "MERMAIDING",
	101: "SPEARFISHING",
	102: "JUMP_ROPE",
	103: "TRACK_RUNNING",
	104: "CALISTHENICS",
	105: "E_BIKING",
	106: "E_MTB",
	107: "BACKCOUNTRY_SKIING",
	108: "WHEELCHAIR",
	109: "HAND_CYCLING",
	110: "SPLIT_BOARDING",
	111: "BIATHLON",
	112: "MEDITATION",
	113: "FIELD_HOCKEY",
	114: "CYCLOCROSS",
	115: "VERTICAL_RUN",
	116: "SKI_MOUNTAINEERING",
	117: "SKATE_SKIING",
	118: "CLASSIC_SKIING",
	119: "CHORES",
	120: "PILATES",
	121: "NEW_YOGA",
}

// ActivityName returns the ActivityType enum name for id, or "act=<id>" if id
// is unknown (covers the 89/98 gaps and any IDs added in newer APK versions).
func ActivityName(id int) string {
	if name, ok := activityNames[id]; ok {
		return name
	}
	return fmt.Sprintf("act=%d", id)
}
